version: '3'

services:
  server:
    build:
      context: ./server
    restart: always
    ports:
      - '5000:5000'
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./.env
    depends_on:
      - mongo
    networks:
      - app-network

  client:
    build:
      context: ./client
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - app-network
    depends_on:
      - server

  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data: