services:
  - type: web
    name: movie-barcode-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false

  - type: web
    name: movie-barcode-frontend
    runtime: static
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: movie-barcode-api
          type: web
          property: url

databases:
  - name: movie-barcode-db
    databaseName: movie_barcode
    user: barcode_user
    plan: free